/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.vexide.hydrozoa.plugin.bindings

import dev.vexide.hydrozoa.plugin.bindings.tasks.GenerateBindingsTask
import org.gradle.api.Project
import org.gradle.api.Plugin

@Suppress("unused")
class BindingsGeneratorPlugin : Plugin<Project> {
    override fun apply(project: Project) {
        project.tasks.register("generateBindings", GenerateBindingsTask::class.java) { task ->
            task.group = "build"
            task.description = "Generates bindings for the Hydrozoa SDK"
        }
    }
}

