[libraries]

[plugins]
teavm = { id = "org.teavm", version = "0.10.2" }
jreleaser = { id = "org.jreleaser", version = "1.15.0" }
publish = { id = "com.gradle.plugin-publish", version = "1.2.1" }

[versions]
kotlin = "2.1.20"